Current user sync url fixed
ahmdrz/goinsta pull request #319
Opened 2020-08-16 10:56 UTC by ffurkanhas

When syncing current user's info url should be "accounts/current_user/?edit=true"

2020-08-31 08:02 UTC, ahmdrz requested changes

2020-08-31 08:02 UTC, ahmdrz commented on const.go
> +	urlCurrentUser   = "accounts/current_user/?edit=true"
It's better to fill `Query` in the current_user function.

2020-12-06 14:28 UTC, felipeinf approved these changes

2020-12-12 12:41 UTC, felipeinf approved these changes

2020-12-12 13:03 UTC, ffurkanhas commented
Pull request approved but it is not merged. Do you have any idea? @felipeinf

2021-01-18 21:20 UTC, closed without merging